# Generated by Django 4.1.3 on 2022-11-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221120_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False, 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='discover',
            options={'managed': False, 'verbose_name_plural': 'Discoveries'},
        ),
        migrations.AlterModelOptions(
            name='diseasetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specialize',
            options={'managed': False, 'verbose_name_plural': 'Specializations'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
    ]
