# Generated by Django 4.1.3 on 2022-11-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_country_options_alter_discover_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasetype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='diseasetype',
            table='DiseaseType',
        ),
    ]
